#ifndef KERNEL_SYSTEMMODULES_FILESYSTEM_DEVICEDRIVERS_DMXDRIVER_H_
#define KERNEL_SYSTEMMODULES_FILESYSTEM_DEVICEDRIVERS_DMXDRIVER_H_

#include "../deviceDrivers/fileOperations.h"

extern FileOperations_t dmxDriver;

#endif /* KERNEL_SYSTEMMODULES_FILESYSTEM_DEVICEDRIVERS_DMXDRIVER_H_ */
