/*
 * syscallNumbers.h
 *
 *  Created on: 05.04.2017
 *      Author: Jasmin
 */

#ifndef KERNEL_SYSTEMMODULES_SYSCALLS_SYSCALLNUMBERS_H_
#define KERNEL_SYSTEMMODULES_SYSCALLS_SYSCALLNUMBERS_H_

#define LED_SYSCALL 1

#endif /* KERNEL_SYSTEMMODULES_SYSCALLS_SYSCALLNUMBERS_H_ */
