#ifndef KERNEL_SYSTEMMODULES_SYSTEMCALLS_DISPATCHER_H_
#define KERNEL_SYSTEMMODULES_SYSTEMCALLS_DISPATCHER_H_

#include "systemCallArguments.h"

int dispatcher_dispatch(SysCallArgs_t args);

#endif /* KERNEL_SYSTEMMODULES_SYSTEMCALLS_DISPATCHER_H_ */
