#ifndef KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLNUMBER_H_
#define KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLNUMBER_H_

typedef enum {
    SYSCALL_LED,
    SYSCALL_FILE_OPEN,
    SYSCALL_FILE_READ,
    SYSCALL_FILE_WRITE,
    SYSCALL_FILE_CLOSE
} SystemCallNumber;

#endif /* KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLNUMBER_H_ */
