#ifndef KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLARGUMENTS_H_
#define KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLARGUMENTS_H_

typedef struct {
    int syscallNumber;
    int a;
    int b;
    int c;
} SysCallArgs_t;

#endif /* KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLARGUMENTS_H_ */
