#ifndef KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLNUMBER_H_
#define KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLNUMBER_H_

typedef enum {
    SYSCALL_DMX_SEND,
    SYSCALL_DMX_CREATE_PACKET,
    SYSCALL_LED,
    SYSCALL_FILE_OPEN,
    SYSCALL_FILE_READ,
    SYSCALL_FILE_WRITE,
    SYSCALL_FILE_CLOSE,
    SYSCALL_READDIR,
    SYSCALL_SEMAPHORE_INIT,
    SYSCALL_SEMAPHORE_P,
    SYSCALL_SEMAPHORE_V
} SystemCallNumber;

#endif /* KERNEL_SYSTEMMODULES_SYSTEMCALLS_SYSTEMCALLNUMBER_H_ */
