#ifndef KERNEL_SYSTEMMODULES_FILESYSTEM_CONFFS_H_
#define KERNEL_SYSTEMMODULES_FILESYSTEM_CONFFS_H_

#include "vfs.h"

extern FileSystem_t confFs;

#endif /* KERNEL_SYSTEMMODULES_FILESYSTEM_CONFFS_H_ */
