#ifndef KERNEL_SYSTEMMODULES_FILESYSTEM_DEVICEDRIVERFS_H_
#define KERNEL_SYSTEMMODULES_FILESYSTEM_DEVICEDRIVERFS_H_

#include "vfs.h"

extern FileSystem_t deviceDriverFs;

#endif /* KERNEL_SYSTEMMODULES_FILESYSTEM_DEVICEDRIVERFS_H_ */
