#ifndef KERNEL_SYSTEMMODULES_FILESYSTEM_PROCESSFS_H_
#define KERNEL_SYSTEMMODULES_FILESYSTEM_PROCESSFS_H_

#include "vfs.h"

extern FileSystem_t processFs;

#endif /* KERNEL_SYSTEMMODULES_FILESYSTEM_PROCESSFS_H_ */
