#ifndef KERNEL_SYSTEMMODULES_FILESYSTEM_SDCARDFSFS_H_
#define KERNEL_SYSTEMMODULES_FILESYSTEM_SDCARDFSFS_H_

#include "vfs.h"

extern FileSystem_t sdCardFs;

#endif /* KERNEL_SYSTEMMODULES_FILESYSTEM_SDCARDFS_H_ */
